# This Workflow is used for when a push is made to the default branch
name: Push Handeling

on: push

jobs:
      
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci
    
      - name: Build
        run: npm run build

      - name: Commit Dist Folder
        continue-on-error: true
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add dist/**
            git commit dist/** -m "chore(main): npm run build"
            git push